name: CI web-site_mtsbank.ru

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 1. Сборка + запуск тестов
      - name: Build and run tests
        run: mvn clean test

      # 2. Генерация Allure-отчёта (HTML)
      - name: Generate Allure report
        run: mvn allure:report

      # 3. Загрузка Allure-отчёта как артефакта
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      # 4. Скачивание Allure-отчета для отправки в Telegram
      - name: Download Allure Report
        if: always()
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: allure-report

      # 5. Отправка Allure-отчета в Telegram ссылкой
      - name: Notify Telegram with Allure Report Link
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ CI Workflow завершен успешно. Скачайте Allure Report по ссылке: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"


