name: CI web-site_mtsbank.ru

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check Maven version
        run: mvn -version

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Debug test resources
        run: ls -la src/test/resources

      # 1. Сборка + запуск тестов
      - name: Build and run tests
        run: mvn clean test

      # 2. Проверка результатов тестов Surefire
      - name: Debug Surefire Reports
        run: |
          echo "Surefire reports:"
          ls -la target/surefire-reports || echo "Surefire reports not found"
          cat target/surefire-reports/*.txt || echo "No Surefire report files found"

      # 3. Генерация Allure-отчёта (HTML)
      - name: Verify Allure Results
        run: |
          if [ ! -d "allure-results" ]; then
            echo "No Allure results found. Skipping report generation."
            exit 0
          fi

      - name: Generate Allure report
        run: mvn allure:report

      # 4. Загрузка Allure-отчёта как артефакта
      - name: Debug Allure Report Path
        run: ls -la build/reports/allure-report

      - name: Upload Allure Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: build/reports/allure-report

      # 5. Скачивание Allure-отчета для отправки в Telegram
      - name: Download Allure Report
        if: success()
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: allure-report

      # 6. Отправка уведомлений в Telegram
      - name: Notify Telegram Success
        if: success()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ CI Workflow завершен успешно. Скачайте Allure Report по ссылке: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Notify Telegram Failure
        if: failure()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="❌ CI Workflow завершен с ошибкой. Проверьте логи: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
